Sumcheck
lurk-lab/solidity-verifier pull request #18
Opened 2023-06-28 20:05 UTC by mpenciak

2023-07-05 10:08 UTC, storojs72 commented
As far as I see, new file `src/sumcheck.sol` is being added and also there are some changes on KeccakTranscript. How do you debug and test your implementation? And what part of Nova sumcheck protocol is being implemented? Just for pointer - we expect [this](https://github.com/lurk-lab/Nova/blob/solidity-verifier/src/spartan/sumcheck.rs#L22) one.

2023-07-11 18:37 UTC, storojs72 commented
@mpenciak , I added basic unit-testing for primary part of sumcheck computation. There were some issues with using the right modulus and negation. Having this as an example, it should be easier to implement secondary part and update data contract as well as Python generator script.

2023-07-30 11:27 UTC, huitseeker approved these changes
Thanks a lot @mpenciak !

2023-07-31 14:57 UTC, storojs72 requested changes
I like the idea of having bunch of `absorb` functions, each taking its own type of input. It seems to be a bit more ergonomic than what I used in [pp-spartan](https://github.com/lurk-lab/solidity-verifier/blob/pp-spartan/src/NovaVerifierAbstractions.sol#L119) branch, where I have similar bunch of `toTranscriptBytes` functions and I have to introduce a redundant intermediate `uint8[] memory` variable all the time, when I need to invoke `absorb`.

At the same time, after taking draft code from early version of this PR and adapting it for usage in [pp-spartan branch](https://github.com/lurk-lab/solidity-verifier/tree/pp-spartan), I have couple of remarks:

I think a lot of Sumcheck's logic can be implemented in a more generic way: in some places we can pass modulus as a uint256 variable (either Vesta or Pallas), also we can use passing function as a parameter if we need to use particular negation. Also, structures that operates with just `uint256` can be defined only once.

It looks like you implemented some more types of evaluations, however, from my experience, the pp-spartan verification uses only sumcheck over `UniPoly` polynomials ([this](https://github.com/lurk-lab/solidity-verifier/blob/pp-spartan/src/blocks/Sumcheck.sol) implementation is sufficient for e2e pp-spartan verification). Though I didn't check if other polynomials are used while [IPA](https://github.com/lurk-lab/Nova/blob/solidity-verifier-pp-spartan/src/spartan/ppsnark.rs#L2031) (as it is going to be replaced with KZG/Zeromorph eventually). Anyway, if these logic is useful and we want to keep it as a building block (yet unused in high-level verification), it needs to be somehow tested.

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +        require(proof.compressed_polys.length == num_rounds, "Wrong number of polynomials");
It is very helpful while debugging if we put library and function name into exception string, like following:
`"[PrimarySumcheck::verify] Wrong number of polynomials"`

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +    struct MLPoly {
As far as I see, these structs (MLPoly, SparseEntry, SparsePoly, UniPoly, CompressedUniPoly) are identical for both PallasPolyLib and VestaPolyLib. Can't we have them defined in some single place?

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/sumcheck-data-contract-gen.py
> +print(data_contract_body)
newline?

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +                result = mulmod(result, addmod(1, Pallas.negateBase(r[j]), Pallas.P_MOD), Pallas.P_MOD);
We can make this function generic by passing the correct modulus and negation function as parameters

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +    function evaluate(MLPoly calldata P, uint256[] calldata r) public pure returns (uint256 result) {
We can make this function generic, by forcing caller to pass correct modulus as parameter

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +    function newML(uint256[] memory Z, uint64 numvars) public pure returns (MLPoly memory) {
I think we don't need two identical `newML` functions in PallasPolyLib and VestaPolyLib as they don't need to know the curve

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +    function boundPolyVarTop(MLPoly calldata P, uint256 r) public pure returns (MLPoly memory) {
Same. By passing modulus as parameter, we can make this function generic

2023-07-31 14:57 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +    function compress(UniPoly memory poly) public pure returns (CompressedUniPoly memory result) {
Do we need compression somewhere? I didn't find its usage. If it is still necessary, we need to test it either explicitly by introducing unit-test or implicitly by using it in some higher level function that is tested.

2023-08-01 17:55 UTC, mpenciak commented on src/verifier/step4/SumcheckLogic.sol
> +    function toTranscriptBytes(UniPoly memory poly) public pure returns (uint8[] memory) {
I think that might introduce a dependency cycle `KeccakTranscript` -> `SumcheckLogic` -> `KeccakTranscript`.

A way around it is to separate out the polynomial library and sumcheck library files, which actually makes some sense. I'll try to do this refactor now.

2023-08-02 09:53 UTC, storojs72 approved these changes
LGTM now! Thanks!

2023-08-02 09:53 UTC, storojs72 commented on src/verifier/step4/SumcheckLogic.sol
> +    struct SumcheckProof {
I think this struct can also be moved to PolyLib as soon as it deals just with uint256s internally.

2023-08-03 17:57 UTC, merged